stages:
- build
Qt5.15.2-msvc2019-64bit:
  stage: build
  script:
    - conan user -p 20010131Lys! -r liyaosong admin
    - mkdir build
    - cd build
    - qmake ../BuffetMealsSystem.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
    - jom qmake_all
    - cd lib
    - jom install
    - jom conanupload 
    
# Qt5.15.5-linux-gcc9.3.0-arm-64bit:
#   tags:
#     - linux_arm64
#   stage: build
#   script:
#     - mkdir 5.15.5_build
#     - cd 5.15.5_build
#     - /home/lys/Qt/5.15.5/bin/qmake ../BuffetMealsSystem.pro
#     - make qmake_all
#     - make -j4

