stages:
- build
Qt5.15.2-msvc2019-64bit:
  stage: build
  script:
    - mkdir build
    - cd build
    - qmake ../BuffetMealsSystem.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
    - jom qmake_all
    - jom
    
Qt-5.15.5-linux-gcc9.3.0-arm-64bit:
  tags:
    - linux_arm64
  stage: build
  script:
    - mkdir 5.15.5_build
    - cd 5.15.5_build
    - chmod +x /home/lys/Qt/5.15.5/qmake
    - /home/lys/Qt/5.15.5/qmake ../BuffetMealsSystem.pro
    - make qmake_all
    - make -j4

